# Change these first
owner: fanqianghub # Your GitHub organization or username, where this repository lives
repo: nodestatus # The name of this repository

sites:
  - name: 狮云 - 网站 app.cloudlion.me
    url: https://app.cloudlion.me
  - name: 狮云 - 博客 lwjyj.com
    url: https://www.lwjyj.com

status-website:
  theme: light
  cname: nodestatus.fanqianghub.com
  logoUrl: https://fanqianghub.com/wp-content/uploads/2023/10/cloudlion.png
  # baseUrl: /your-repo-name
  name: 狮云 - 服务状态
  introTitle: "**狮云**网站与服务状态监控"
  introMessage: 节点状态请访问[节点监控网站](https://stats.uptimerobot.com/5kK7BIg6zp)
  navbar:
    - title: 狮云官网
      href: https://app.cloudlion.me
    - title: 导航页
      href: https://fanqianghub.com

      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
NOTIFICATION_TELEGRAM: true
NOTIFICATION_TELEGRAM_BOT_KEY: 6510052551:AAHa7E_XgoHcxkVhzaXmzsPRUHniVQ18Sw8
NOTIFICATION_TELEGRAM_CHAT_ID: 1001821741740
