# Change these first
owner: fanqianghub # Your GitHub organization or username, where this repository lives
repo: nodestatus # The name of this repository

sites:
  - name: 狮云 - 网站 app.cloudlion.me
    url: https://app.cloudlion.me
  - name: 狮云 - 博客 lwjyj.com
    url: https://www.lwjyj.com
  - name: 节点 - 美国 US
    check: "tcp-ping"
    url: https://us.cloudfast.vip
    port: 443
  - name: 节点 - 英国 UK
    check: "tcp-ping"
    url: https://uk.cloudfast.vip
    port: 443
  - name: 节点 - 日本 JP
    check: "tcp-ping"
    url: https://jp.cloudfast.vip
    port: 443
  - name: 节点 - 新加坡 SG
    check: "tcp-ping"
    url: https://sg.cloudfast.vip
    port: 443
    - name: 节点 - 香港 HK
    check: "tcp-ping"
    url: https://hk.cloudfast.vip
    port: 443
  - name: 节点 - 台湾 TW
    check: "tcp-ping"
    url: https://tw.cloudfast.vip
    port: 443

status-website:
  theme: light
  cname: nodestatus.fanqianghub.com
  logoUrl: https://fanqianghub.com/wp-content/uploads/2023/10/cloudlion.png
  # baseUrl: /your-repo-name
  name: 狮云 - 服务状态
  introTitle: "**狮云**网站与服务状态监控"
  introMessage: 
  navbar:
    - title: 狮云官网
      href: https://app.cloudlion.me
    - title: 导航页
      href: https://fanqianghub.com

      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
NOTIFICATION_TELEGRAM: true
NOTIFICATION_TELEGRAM_BOT_KEY: 6510052551:AAHa7E_XgoHcxkVhzaXmzsPRUHniVQ18Sw8
NOTIFICATION_TELEGRAM_CHAT_ID: 1001821741740
