# Change these first
owner: fanqianghub # Your GitHub organization or username, where this repository lives
repo: nodestatus # The name of this repository

sites:
  - name: 导航 - fanqianghub.com
    url: https://fanqianghub.com
  - name: 论坛 - forum.fanqianghub.com
    url: https://forum.fanqianghub.com
  - name: 博客 - blog.fanqianghub.com
    url: https://blog.fanqianghub.com

status-website:
  theme: light
  cname: nodestatus.fanqianghub.com
  logoUrl: https://fanqianghub.com/wp-content/uploads/2023/10/fqhub_logo_icon_round.png
  # baseUrl: /your-repo-name
  name: 翻墙中心 - 服务状态
  introTitle: "**翻墙中心**网站与服务状态监控"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: 导航页
      href: https://fanqianghub.com
      

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
