# Change these first
owner: fanqianghub # Your GitHub organization or username, where this repository lives
repo: nodestatus # The name of this repository

sites:
  - name: 狮云 - 网站
    url: https://app.cloudlion.me
  - name: 狮云 - 博客
    url: https://cloudlion.me
  - name: 入口节点 - 上海移动
    check: "tcp-ping"
    url: https://shyd.zz.cloudfast.vip
    port: 14899
  - name: 入口节点 - 广州移动
    check: "tcp-ping"
    url: https://gzyd.zz.cloudfast.vip
    port: 34373
  - name: 入口节点 - 北京联通
    check: "tcp-ping"
    url: https://bjlt.zz.cloudfast.vip
    port: 10138
  - name: 入口节点 - 唯云莞港IPLC
    check: "tcp-ping"
    url: https://wywg.zx.cloudfast.vip
    port: 443

status-website:
  theme: light
  cname: nodestatus.fanqianghub.com
  logoUrl: https://fanqianghub.com/wp-content/uploads/2023/10/cloudlion.png
  # baseUrl: /your-repo-name
  name: 狮云 - 服务状态
  introTitle: "**狮云**网站与服务状态监控"
  introMessage: 
  navbar:
    - title: 狮云官网
      href: https://app.cloudlion.me
    - title: 导航页
      href: https://fanqianghub.com

      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
